name: serve
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Running whatsapp
        run: |
          npm install
          node index.js
      - name: Done! Running server 8 jam
        run: |
          bash ./loop.sh
